### ISSUE TITLE
No such file: MOFA_depmap23Q2_Factors97_factors.csv

### ISSUE THREAD

**Issue by eyheb** [QuantitativeBiology/PhenPred#1]
Hi,

I followed the steps in the README and ran the demo as per the default tutorial. However, after the 500 epochs training finishes, I encountered an error indicating that the file MOFA_depmap23Q2_Factors97_factors.csv could not be found. I searched through the entire codebase and found that the function responsible for generating this file doesn't seem to be called. Could you please guide me on how I can resolve this issue?

Thank you!

**Comment by ZhaoxiangSimonCai** [comment]
Hi,

Thank you for trying our method. The intermediate files can be downloaded from the Figshare site as mentioned in our paper. The URL for the MOFA files is here https://figshare.com/account/projects/177699/articles/24420631
